admin/admin/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path
from django.conf.urls import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(('apps.profiles.urls', 'profiles'), namespace="profiles")),
    path('states/', include(('apps.states.urls', 'states'), namespace="states")),
    path('prueba/', include(('apps.prueba.urls', 'locations'), namespace="prueba")),
    path('bancoPregunta/', include(('apps.bancoPregunta.urls', 'locations'), namespace="bancoPregunta")),
    path('bancoPregunta/', include(('apps.bancoPregunta.urls', 'preguntas'), namespace="bancoPregunta"))
]

admin/apps/bancoPregunta/urls.py
from django.urls import path
from apps.bancoPregunta.views import *
# from apps.locations.apiViews import *
from apps.bancoPregunta.views import *

urlpatterns = [
    path('readResultados/', read_resultado_view, name='readResultados'),
    path('createPregunta/', create_pregunta_view, name='createPregunta')
    # path('readDepartament/', read_departament_view, name='readDepartament'),
    # path('readCity/', read_city_view, name='readCity'),
    # path('readOffice/', read_office_view, name='readOffice'),
    # path('createOffice/',create_office_view, name='createOffice'),
	# path('updateOffice/<int:pk>',update_office_view, name='updateOffice'),
    #------------URLS APIS----------------------------------------------
	# path('apiDepartament',api_departament, name='apiDepartament'),
	# path('apiCity',api_city, name='apiCity'),
    # path('apiOffice',api_office, name='apiOffice'),
    # path('apiOffice/<int:pk>',api_office, name='apiOffice'),

    
]

admin/apps/profiles/urls.py
from django.urls import path
from apps.profiles.views import *

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
	path('home/',home_view, name='home'),
    path('readTipoDocumento/', read_tipoDocumento_view, name='readTipoDocumento'),
    path('createEstudiante/',create_estudiante_view, name='createEstudiante'),
    path('updateEstudiante/<int:pk>',update_estudiante_view, name='updateEstudiante'),
	path('readEstudiante/',read_estudiante_view, name='readEstudiante'),
	path('readEstudiante/<int:pk>',read_estudiante_view, name='readEstudiante'),

]

admin/apps/prueba/urls.py
from django.urls import path
from apps.prueba.views import *
# from apps.locations.apiViews import *

urlpatterns = [
    path('readMateria/', read_materia_view, name='readMateria'),
    path('readGrado/', read_grado_view, name='readGrado'),
    # path('readDepartament/', read_departament_view, name='readDepartament'),
    # path('readCity/', read_city_view, name='readCity'),
    # path('readOffice/', read_office_view, name='readOffice'),
    # path('createOffice/',create_office_view, name='createOffice'),
	# path('updateOffice/<int:pk>',update_office_view, name='updateOffice'),
    #------------URLS APIS----------------------------------------------
	# path('apiDepartament',api_departament, name='apiDepartament'),
	# path('apiCity',api_city, name='apiCity'),
    # path('apiOffice',api_office, name='apiOffice'),
    # path('apiOffice/<int:pk>',api_office, name='apiOffice'),

    
]

admin/apps/states/urls.py
from django.urls import path
from apps.states.views import *

urlpatterns = [
	path('readStates/',read_states_view, name='readStates'),

]
    

admin/templates/general/footer.html
<div class="footer mt-auto py-4 text-light bg-Cprimary ">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-md-6">
                <b class="text-md-left text-center mt-3 text-dark">Copyright © 2022 Simusaber 3 y 5 - Derechos Reservados</b>

            </div>
            <div class="col-12 col-md-6">
                <div class="row ">
                    <div class="col-12 col-md-5 text-center px-0">
                        <a class="text-dark  text-md-right mr-md-3" href="#"><b>Terminos y Condiciones</b></a><b class="text-dark">|</b>
                    </div>
                    <div class="col-12 col-md-7 px-0 text-center">
                        <a class="text-dark text-md-left" href="#"> <b>Politica de Privacidad de Datos</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

admin/templates/general/header.html
{% load staticfiles %}
<nav class="row container-fluid navbar navbar-expand-lg  bg-Cgraylight py-0 bg-dark">
  <div class="text-white ml-2 ml-md-5 col-7 col-md-2">
    <a class="ml-md-5" href="">
      <a href="http://127.0.0.1:8000/profiles/home/">
        <img src="{% static 'images/logo_simusaber.png' %}"  class="h-50 w-50"> 
      </a>
    </a>
  </div>
  <button class="navbar-toggler mr-5" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse mt-3 mt-md-0 small col-md-8" id="navbarSupportedContent">
    <ul class="navbar-nav text-md-center  text-left flex-grow-1 d-flex justify-content-md-center">
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class= href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-home fa-3x text-Csecondary">
              <div class="h6 m-0">
                <h5>Inicio</h5>
              </div>
            </i>
          </a>
        </div>
      </li>
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-book fa-3x text-Cprimary">
              <div class="h6 m-0">
                <h5>Pruebas</h5>
              </div>
            </i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item " href="{% url 'prueba:readMateria'%}">Materias</a> 
            <a class="dropdown-item " href="{% url 'prueba:readGrado'%}">Grados</a> 
          </div>
        </div>
      </li>
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-hand-paper-o fa-3x text-Csecondary">
              <div class="h6 m-0">
                <h5>Apoyo</h5>
              </div>
            </i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          </div>
        </div>
      </li>
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-users fa-3x text-Cprimary">
              <div class="h6 m-0">
                <h5>Perfiles</h5>
              </div>
            </i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item " href="{% url 'profiles:readTipoDocumento'%}">Tipos de Documentos</a> 
            <a class="dropdown-item " href="{% url 'profiles:readEstudiante'%}">Estudiantes</a> 
          </div>
        </div>
      </li>
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-star-half-o fa-3x text-Csecondary">
              <div class="h6 m-0">
                <h5>Estados</h5>
              </div>
            </i>
          </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <a class="dropdown-item " href="{% url 'states:readStates'%}">Estados</a> 
          </div>
        </div>
      </li>
      <li class="nav-item text-center mx-2 nav-item dropdown">
        <div class="nav-link">
          <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-server fa-3x text-Cprimary">
              <div class="h6 m-0">
                <h5>Banco Pregunta</h5>
              </div>
            </i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item " href="{% url 'bancoPregunta:readResultados'%}">Resultados</a>
            <a class="dropdown-item " href="{% url 'bancoPregunta:createPregunta'%}">Preguntas</a> 
          </div>
        </div>
      </li>
    </ul>
    <div class="justify-content-md-end justify-content-center">
      <ul class="navbar-nav text-right flex-grow-1 my-0 d-flex justify-content-end">
        <li class="nav-item text-center mx-2 nav-item dropdown">
          <div class="row"> 
            <div class="nav-link col-12 col-md-3 mt-md-2">
              <a class="dropdown-toggle text-Cprimary " href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user-circle-o fa-3x text-Ctertiary">
                  <div class="h6 m-0">
                    <h6 >{{user.get_full_name}}</h6>
                    <h6 >({{user.groups.all.0.name}})</h6>
                  </div>
                </i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">        
                <a class="dropdown-item " href="{% url 'profiles:logout' %}">Cerrar sesión<i class=" ml-2 fa fa-sign-in text-Cprimary " aria-hidden="true"></i></a>
              </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

admin/templates/general/home.html
{% extends 'general/master.html' %}
{% block content %}
{% load staticfiles %}

<div class="container-fluid">
  <div class="row min-vh-C76 mr-10 bg-CimageHome full-Cimage">
    <div class="col-12">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-center">
          <h1 class="fw-light"><b>Bienvenido a 
            <img class="img-fluid py-2" alt="Responsive image" src="{% static 'images/logoSimusaber_largo.png' %}"></b></h1>
        </div>
      </div>
    </div>  
</div>
  

{% endblock %}

admin/templates/general/login.html
<!DOCTYPE html>
<html>
  {% load staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Simusaber 3 y 5</title>
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="{% static 'bootstrap4.6/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'general/general.css' %}?{{version_static}}">  
</head>

<body class="bg-Clogin full-Cimage text-dark">   
  <div class="container-fluid">
    <div class="row h-100 pt-5 align-items-center">
      <div class="col-6 offset-3 col-md-4 offset-4 card mt-5 rounded  shadow">
          <div class="row justify-content-center">
            <img class="img-fluid py-2" alt="Responsive image" src="{% static 'images/logo_simusaber1.png' %}">            
          </div>
          <hr">
          <div class="row  justify-content-center">
            <h3 class="text-Cprimary"><b>¡Bienvenido!</b></h3>
          </div>
          <div class="row  justify-content-center">
            Ingresa a tu Cuenta
          </div>
          <hr>
        <div class="card-body ">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Usuario</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="fa fa-envelope-open-o" aria-hidden="true"></i></span>
                    </div>
                    <input type="text" id="login_username" placeholder="Ingresa tu Usuario" class="form-control"
                    name="username">
                  </div>
                  <div class="help-block with-errors text-danger">{{form.errors.username}}</div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label>Contraseña</label>
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-unlock" aria-hidden="true"></i></span>
                      </div>
                      <input type="password" id="login_password" placeholder="Ingresa tu Contraseña" class="form-control"
                        name="password">
                      <div class="input-group-prepend">
                        <span class="text-Csecondary input-group-text bg-white border-left-0">
                          <i class="fa js-eye-show fa-eye-slash"></i>
                        </span>
                      </div>
                    </div>
                    <div class="help-block with-errors text-danger">{{form.errors.password}}</div>
                </div>
              </div>
            </div>
            <div class="row mt-3 mb-3">
              <div class="col-md-12">
                <button type="submit" class="btn text-white bg-Csecondary btn-lg btn-block">
                  Ingresar
                </button>
              </div>
            </div>
            <div class="row mt-2 mb-3 justify-content-center">
              <a class="text-Csecondary" data-toggle="modal" data-target="#reset_password_modal" href="#">¿Olvidaste Tu Contraseña?</a>
            </div>
            {% for err in form.non_field_errors %}
            <div class='row mx-0 alert-danger'>
              {{err}}
            </div>
            {% endfor %}
          </form>        
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="reset_password_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">          
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="row justify-content-center mb-2">
            <h4 class="modal-title text-center" id="exampleModalLabel"><b>Restablecer Contraseña</b></h4>
          </div>
          <div role="tabpanel" class="tab-pane" name="P3">
            <div class="row justify-content-center">
                <div class="col-11">
                      <div role="tabpanel">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" name="Paso1">
                                <form class="row justify-content-center js-form_Reset">
                                    <div class="col-11">
                                        <div class="row pt-md-1 pb-md-1 h8 justify-content-center ">
                                          Ingresa tu correo electrónico y te enviaremos un código de verificación para que puedas recuperar la contraseña de tu cuenta.
                                        </div>
                                        <div class="row pt-md-3 pb-md-3">
                                            <input type="text" name="emailReset" class="form-control" placeholder="Correo Electrónico">
                                        </div>
                                        <div class="row alert-danger my-2 mx-2 pt-1 text-center" name='Mensaje_error' id="containerError_Mensaje" style="display: none;">
                                          <label id="error_Mensaje"></label>
                                        </div>
                                        <div class="row mb-3 mt-2">
                                            <button type="submit" name="submitReset" class="btn btn-block font-weight-bold bg-Cprimary text-white"><span class="spinner-border spinner-border-sm text-white d-none" role="status" aria-hidden="true"></span>Solicitar Código</button>
                                        </div>	
                                    </div>
                                </form>
                            </div>
                            <div role="tabpanel" class="tab-pane" name="Paso2">
                                <form class="row justify-content-center js-form_Verify">
                                    <div class="col-11">
                                        <div class="row justify-content-center">
                                              <div class="col-12">	
                                                  <div class="row justify-content-center">
                                                      <div class="col-12 mt-5 pb-5 h5 font-weight-bold text-center">
                                                        VERIFICA QUE ERES TÚ
                                                      </div>
                                                  </div>				      				
                                              </div>
                                          </div>	   
                                          <div class="row">
                                              <div class="col-12">
                                                <div class="row pb-md-3">
                                                    <input type="text" name="codeVerify" class="form-control text-center" placeholder="X X X X X X ">
                                                </div>
                                                <div class="row alert-danger my-2 mx-2 pt-1 text-center" name='Mensaje_error' id="containerError_Mensaje" style="display: none;">
                                                  <label id="error_Mensaje"></label>
                                                </div>
                                              </div>
                                          </div>	 	
                                        <div class="row mx-0 mt-5">
                                            <button type="button" class="btn btn-block">
                                                <div class="row justify-content-center">
                                                    <div class="col-12 h8 text-center ">
                                                        <u class="js-btnPassOne text-Csecondary">No recibí un código de verificación.</u>
                                                    </div>
                                                </div>
                                            </button>
                                        </div>  
                                        <div class="row mt-1">
                                            <button type="submit" name="submitVerify" class="btn btn-block bg-Cprimary text-white font-weight-bold"><span class="spinner-border spinner-border-sm text-white d-none" role="status" aria-hidden="true"></span>Verificar</button>
                                        </div>		 
                                    </div>
                                </form>
                            </div>
                            <div role="tabpanel" class="tab-pane" name="Paso3">
                                <form class="row justify-content-center js-form_Confirm">
                                    <div class="col-11">
                                        <div class="row pt-md-3 h8 justify-content-center text-center">
                                            <h5>Introduce tu nueva contraseña</h5>
                                        </div>
                                        <div class="row pt-md-2">
                                            <div class="input-group">
                                              <input type="password" name="new_password1Confirm" class="form-control" placeholder="Contraseña Nueva">
                                              <div class="input-group-prepend">
                                                <span class="text-Csecondary input-group-text bg-white border-left-0">
                                                  <i class="fa js-eye-show fa-eye-slash"></i>
                                                </span>
                                              </div>
                                            </div>
                                        </div>
                                        <div class="row pt-md-3 pb-md-5">
                                            <div class="input-group">
                                              <input type="password" name="new_password2Confirm" class="form-control" placeholder="Confirmar Contraseña Nueva">
                                              <div class="input-group-prepend">
                                                <span class="text-Csecondary input-group-text bg-white border-left-0">
                                                  <i class="fa js-eye-show fa-eye-slash"></i>
                                                </span>
                                              </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <button type="submit" name="submitConfirm" class="btn btn-block font-weight-bold bg-Cprimary text-white"><span class="spinner-border spinner-border-sm text-white d-none" role="status" aria-hidden="true"></span>Finalizar</button>
                                        </div>	
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>	 
                </div>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap JS -->
  <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap4.6/js/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'general/general.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'general/config.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'general/apis.js' %}?{{version_static}}"></script>
  <script type="text/javascript" src="{% static 'apps/profiles/generalProfile.js' %}?{{version_static}}"></script>
</body>

</html>

admin/templates/general/master.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Simusaber 3 y5 </title>
        <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static 'bootstrap4.6/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}"> 
        <link rel="stylesheet" href="{% static 'general/general.css' %}?{{version_static}}">   
        <link rel="icon" href="{% static 'images/icono_simusaber.ico' %}">
    </head>
    <body>

        <body class="d-flex flex-column min-vh-100 ">
            <!-- <body class="d-flex flex-column min-vh-100 "> -->
            <!-- <body>   -->
            <header class="mx-0">
                {% include "general/header.html" %}
                <hr class="mb-0">
            </header>
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
            <!-- Modal para eliminar -->
            <div class="modal fade right" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
                aria-hidden="true" data-backdrop="false">
                <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
                    <div class="modal-content">
                        <!--Header-->
                        <div class="modal-header bg-light">
                            <div class="col-12 text-dark text-start font-weight-bold h5 my-2">
                                ¡Espera!
                            </div>
                        </div>
                        <div class="modal-body ml-3">
                            ¿Estás seguro de eliminar este elemento?
                        </div>
                        <div class="modal-footer">
                            <a type="button"
                                class="col-3 mt-2 btn btn-sm bg-Cprimary btn-block text-white waves-effect waves-light"
                                href="">Cancelar
                                <i class="fa fa-times ml-1"></i>
                            </a>
                            <button type="submit" form="createform" name="action" value="delete"
                                class="col-3 btn btn-sm bg-danger btn-block text-white waves-effect waves-light">Eliminar
                                <i class="fa fa-check ml-1"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal: General -->
            <div class="modal fade right {% block modalErrors %}{% endblock%}" id="GeneralModal" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalLabel {% block crudShow %}{% endblock %}" aria-hidden="true" data-backdrop="false">
                <div class="modal-dialog modal-full-height modal-right modal-notify modal-info" role="document">
                    <div class="modal-content">
                        <!--Header-->
                        <div class="modal-header bg-light">
                            <div class="col-10 text-dark text-start font-weight-bold h5 my-2 ml-4">
                                {% block form_modal_title %}
                                {% endblock %}
                            </div>
                        </div>
                        <!--Body-->
                        <div class="modal-body">
                            {%block form_modal_content %}
        
                            {%endblock%}
                        </div>
                        <!--Footer-->
                        <div class="modal-footer">
                            {% block form_modal_footter %}
        
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        
            <footer class="mt-auto">
                {% include "general/footer.html" %}
            </footer>
        

        <!-- Bootstrap JS -->
        <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'jquery/jquery.autocomplete.js' %}"></script>
        <script type="text/javascript" src="{% static 'bootstrap4.6/js/bootstrap.bundle.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'general/general.js' %}?{{version_static}}"></script>
        <script type="text/javascript" src="{% static 'general/config.js' %}?{{version_static}}"></script>
        <script type="text/javascript" src="{% static 'general/apis.js' %}?{{version_static}}"></script>
          
        {% block script %}
        {% endblock %}              
    </body>
</html>