admin/admin/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path
from django.conf.urls import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(('apps.profiles.urls', 'profiles'), namespace="profiles")),
    path('states/', include(('apps.states.urls', 'states'), namespace="states")),
    path('prueba/', include(('apps.prueba.urls', 'locations'), namespace="prueba")),
    path('bancoPregunta/', include(('apps.bancoPregunta.urls', 'locations'), namespace="bancoPregunta")),
    path('bancoPregunta/', include(('apps.bancoPregunta.urls', 'preguntas'), namespace="bancoPregunta"))
]

admin/apps/profiles/urls.py
from django.urls import path
from apps.profiles.views import *

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
	path('home/',home_view, name='home'),
    path('readTipoDocumento/', read_tipoDocumento_view, name='readTipoDocumento'),
    path('createEstudiante/',create_estudiante_view, name='createEstudiante'),
    path('updateEstudiante/<int:pk>',update_estudiante_view, name='updateEstudiante'),
	path('readEstudiante/',read_estudiante_view, name='readEstudiante'),
	path('readEstudiante/<int:pk>',read_estudiante_view, name='readEstudiante'),

]

admin/apps/profiles/models.py
from django.db import models
from django.contrib.auth.models import *
from apps.states.models import *
from apps.prueba.models import *

# Create your models here.

class TipoDocumento(models.Model):

    nombre_documento=models.CharField(max_length=45, null=True)
    
    def __str__(self):
        return self.nombre_documento


class Estudiante(models.Model):
 
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, unique=True, default=1)
    tipo_documento=models.ForeignKey(TipoDocumento, on_delete=models.CASCADE, null=True)
    numero_documento=models.CharField(max_length=45)
    estado = models.ForeignKey(Estado,  on_delete=models.CASCADE, null=True) 

class EstudiantePrueba():
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    prueba=models.ForeignKey(Prueba, on_delete=models.CASCADE, null=True)

admin/apps/profiles/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, F
from django.db.models import Value as V
from django.db.models.functions import Concat
from django.contrib.auth.forms import AuthenticationForm
from apps.profiles.form import *
from apps.prueba.models import *


def user_validate_group(roles=[]):
	def decorator(view_func):
		def arguments(request, *args, **kwargs):
			if request.user.groups.exists():
				if request.user.groups.all()[0].name in roles:
					return view_func(request, *args, **kwargs)
			return redirect('profiles:login')
		return arguments
	return decorator

def user_validate_group(roles=[]):
	def decorator(view_func):
		def arguments(request, *args, **kwargs):
			if request.user.groups.exists():
				if request.user.groups.all()[0].name in roles:
					return view_func(request, *args, **kwargs)
			return redirect('profiles:login')
		return arguments
	return decorator

def login_user(request):
    context={}
    if request.POST:
        form=AuthenticationForm(None, request.POST)
        username = request.POST['username']
        password = request.POST['password']
        if form.is_valid():
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profiles:home')
            else:
                form.add_error(None, "Usuario no encontrado")
        context['form']=form
    return render(request, "general/login.html", context)

def logout_user(request):
    logout(request)
    return redirect('/profiles/login')

@login_required(login_url='/profiles/login')
# @user_validate_group(roles=['Administrator', 'Authorizer'])
def home_view(request):
    return render(request, "general/home.html")

@login_required(login_url='/profiles/login')
def read_tipoDocumento_view(request):
    tipoDocumentos=TipoDocumento.objects.all()
    context={
                'tipoDocumentos':tipoDocumentos,
            }
    return render(request, "profiles/readTipoDocumento.html",context)

def create_estudiante_view(request):
    tipo_documentos = TipoDocumento.objects.all()
    grados = Grado.objects.all()
    if request.method == 'POST': 
        update_request = request.POST.copy()
        update_request.update({'email':request.POST['email'].lower(), 'username':request.POST['email'].lower(),'state':3})
        form = UserForm(update_request)
        form1 = EstudianteForm(update_request, request.FILES)
        if form.is_valid() and form1.is_valid():
            user = form.save(commit = False)
            user.set_password(form.data['new_password'])
            user.save()            
            estudiante = form1.save(commit = False)
            estudiante.user_id = user.id
            estudiante.save()
            return redirect('/profiles/readEstudiante/')   
        else:
            print(form.errors)
            print(form1.errors)
    else:
        form = UserForm()
        form1 = EstudianteForm()
    context = {
        'form': form,
        'form1': form1,
        'tipo_documentos': tipo_documentos,
        'grados': grados,
    }
    return render (request,"profiles/createUpdateEstudiante.html", context)

def update_estudiante_view(request,pk):
    estudiante = Estudiante.objects.get(user__id = pk)
    tipo_documentos = TipoDocumento.objects.all()
    if request.method == 'POST': 
        update_request = request.POST.copy()
        update_request.update({ 'state':3, 'user':estudiante.user.id})
        form = UserUpdateForm(update_request, instance = estudiante.user)
        form1 = EstudianteForm(update_request, request.FILES, instance = estudiante)
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            return redirect('/profiles/readEstudiante/')   
        else:
            print(form.errors)
            print(form1.errors)
    else:
        form = UserUpdateForm()
        form1 = EstudianteForm()
    context = {
        'form': form,
        'form1': form1,
        'tipo_documentos': tipo_documentos,
        'estudiante': estudiante,
    }
    return render (request,"profiles/createUpdateEstudiante.html", context)


def read_estudiante_view(request, pk=None):
    estudiantes = Estudiante.objects.all()
    context = {}
    if pk: 
        estudiante = estudiantes.get(user_id=pk)
        context['estudiante'] = estudiante

    page = request.GET.get('page', 1)
    paginator = Paginator(estudiantes,10)
    try:
        estudiantes = paginator.page(page)
    except PageNotAnInteger:
        estudiantes = paginator.page(1)
    except EmptyPage:
        estudiantes = paginator.page(paginator.num_pages)
    context['estudiantes'] = estudiantes

    return render (request,"profiles/readEstudiante.html", context)

admin/templates/profiles/createUpdateEstudiante.html
{% extends 'general/master.html' %}
{% block script %}
{% endblock %}
{% block content %}
<form class="container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <h1>
            Estudiantes
        </h1>
    </div>
    <div class="row" >
        <div class="col-4">
            <div class="form-group">
                <label>Nombres</label>
                <input type = "text" class = "form-control" name="first_name" autofocus value="{% if form1.errors or form.errors %}{{form.first_name.value}}{% else %}{{estudiante.user.first_name}}{% endif %}">
                <div class='row mx-0 alert-danger'>
                    {%if form.first_name.errors %}
                     {{form.first_name.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label>Apellidos</label>
                <input type = "text" class = "form-control" name="last_name"  value="{% if form1.errors or form.errors %}{{form.last_name.value}}{% else %}{{estudiante.user.last_name}}{% endif %}">
                <div class='row mx-0 alert-danger'>
                    {%if form.last_name.errors %}
                     {{form.last_name.errors}}
                    {%endif%}
                </div>
            </div> 
        </div>
        <div class="col-4 {% if estudiante %} d-none {% endif %}">
            <div class="form-group">
                <label>Correo</label>
                <input type = "email" class = "form-control" name="email"  value="{% if form1.errors or form.errors %}{{form.email.value}}{% else %}{{estudiante.user.email}}{% endif %}">
                <div class='row mx-0 alert-danger'>
                    {%if form.email.errors or form.username.errors%}
                    {{form.email.errors}}
                    {{form.username.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
    <div class="row {% if estudiante %} d-none {% endif %}" >
        <div class="col-6">
            <label>Contraseña</label>
            <div class="input-group">
                <input type="password" name="new_password" class="form-control">
                <div class="input-group-prepend">
                  <span class="input-group-text bg-white border-left-0">
                    <i class="fa js-eye-show text-Cprimary fa-eye-slash"></i>
                  </span>
                </div>
                <div class='row mx-0 alert-danger'>
                    {%if form.new_password.errors %}
                     {{form.new_password.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
        <div class="col-6">
            <label>Confirmar Contraseña</label>
            <div class="input-group">
                <input type="password" name="repeat_password" class="form-control">
                <div class="input-group-prepend">
                  <span class="input-group-text bg-white border-left-0">
                    <i class="fa js-eye-show text-Cprimary fa-eye-slash"></i>
                  </span>
                </div>
                <div class='row mx-0 alert-danger'>
                    {%if form.repeat_password.errors %}
                     {{form.repeat_password.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3" >
        <div class="col-4">
            <div class="form-group">
                <label>Tipo de Documento</label>
                <select class="form-control" name="tipo_documento">
                    <option> - - - - - - - -</option>
                {% for tipo_documento in tipo_documentos %}
                    <option value="{{tipo_documento.id}}" {% if form.errors or form1.errors %}{%if form1.tipo_documento.value|floatformat:'0' == tipo_documento.id|floatformat:'0' %}  selected {% endif %}{% elif tipo_documento.id|floatformat:'0' == estudiante.tipo_documento.id|floatformat:'0'%}selected{% endif %}>{{tipo_documento.nombre_documento}}</option>
                {% endfor %}
                </select>
                <div class='row mx-0 alert-danger'>
                    {%if form1.tipo_documento.errors %}
                     {{form1.tipo_documento.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label>Número de Documento</label>
                <input type = "text" class = "form-control" name="numero_documento"  value="{% if form1.errors or form.errors %}{{form1.numero_documento.value}}{% else %}{{estudiante.numero_documento}}{% endif %}">
                <div class='row mx-0 alert-danger'>
                    {%if form1.numero_documento.errors %}
                     {{form1.numero_documento.errors}}
                    {%endif%}
                </div>
            </div> 
        </div>
        <div class="col-4">
            <div class="form-group">
                <label>Grado</label>
                <select class="form-control" name="grado">
                    <option> - - - - - - - - -</option>
                {% for grado in grados %}
                    <option value="{{grado.id}}" {% if form.errors or form1.errors %}{%if form1.grado.value|floatformat:'0' == grado.id|floatformat:'0' %}  selected {% endif %}{% elif grado.id|floatformat:'0' == estudiante.grado.id|floatformat:'0'%}selected{% endif %}>{{grado.nombre_grado}}</option>
                {% endfor %}
                </select>
                <div class='row mx-0 alert-danger'>
                    {%if form1.grado.errors %}
                     {{form1.grado.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label>Estado</label>
                <select class="form-control" name="is_active">
                   <option value="True"{% if form1.errors or form.errors %}{% if form.is_active == True %} selected {%endif%} {% elif estudiante.is_active == True  %} selected {% endif %}>Activo</option>
                   <option value="False" {% if form1.errors or form.errors %}{% if form.is_active == False %} selected {%endif%}{% elif estudiante.is_active == False  %} selected {% endif %}>Inactivo</option>
                </select>
                <div class='row mx-0 alert-danger'>
                    {%if form.is_active.errors %}
                     {{form.is_active.errors}}
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
    <div class="row mx-0 my-3">
        <button type="submit" class="col-2 btn btn-sm bg-Cprimary btn-block text-white ">Guardar
            <i class="fa fa-check pl-1"></i>
        </button>
        <a class="text-white col-2 btn btn-sm bg-Csecondary text-white ml-2" href="{% url 'profiles:readEstudiante' %}"> Cancelar <i class="fa fa-times pl-1"></i></a>
    </div>
</form>
{% endblock %}

admin/templates/profiles/readEstudiante.html
{% extends 'general/master.html' %}
{% block script %}
{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row mx-0 my-3">
    <div class="col-10 px-0">
      <h2><b>Estudiantes</b></h2>
    </div>
    <div class="col-2">
      <a href="{% url 'profiles:createEstudiante' %}" class="btn bg-Cprimary btn-block text-truncate text-white" ><i class="fa fa-plus-circle pr-2"></i><span>Añadir</span></a>
    </div>
  </div>
  <div class="row mx-0">
    <div class="col-12 p-0">
      <div class="table-responsive">
        <div class="table-wrapper">
          <div class="row mx-0">
            <table class="table table-hover">
              <thead>
                <tr class="bg-Cprimary text-justify text-light shadow">
                  <th class="align-middle text-center">ID</th>
                  <th class="align-middle text-center">Nombres</th>
                  <th class="align-middle text-center">Apellidos</th>
                  <th class="align-middle text-center">Correo</th>
                  <th class="align-middle text-center">Tipo de Documento</th>
                  <th class="align-middle text-center">Número de Documento</th>
                  <th class="align-middle text-center">Grado</th>
                  <th class="align-middle text-center">Estado</th>
                  <th class="align-middle text-center">Opciones</th>
                </tr>
              </thead>
              <tbody>
                {% for estudiante in estudiantes %}
                <tr class="table-light text-justify">
                  <td class="align-middle text-center">{{estudiante.user.id}}</td>
                  <td class="align-middle text-left">{{estudiante.user.first_name}}</td>
                  <td class="align-middle text-left">{{estudiante.user.last_name}}</td>
                  <td class="align-middle text-left">{{estudiante.user.email}}</td>
                  <td class="align-middle text-left">{{estudiante.tipo_documento}}</td>
                  <td class="align-middle text-left">{{estudiante.numero_documento}}</td>
                  <td class="align-middle text-left">{{estudiante.grado}}</td>
                  <td class="align-middle text-left">{%if estudiante.user.is_active %}Activo{%else%}Inactivo{%endif%}
                  </td>
                  <td class="align-middle text-left"><a class="fa fa-pencil-square-o text-Cprimary px-2"  href="{% url 'profiles:updateEstudiante' estudiante.user.id %}"></a>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row my-5">
    <div class="col-10 offset-1 col-md-8 offset-md-2 px-1">
      <div class="row">
        <div class="col-12 px-1">
          <div class="row mx-0 d-flex justify-content-center">
            {% if estudiantes.has_previous %}
            <a class="border-0 text-Cprimary d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="?{{request.GET.urlencode}}&page=1"><i class="fa fa-fast-backward"></i></a>
            {% endif %}
            {% if estudiantes.has_previous %}
            <a class="border-0 text-Cprimary d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="?{{request.GET.urlencode}}&page={{ estudiantes.previous_page_number }}"><i
                class="fa fa-step-backward"></i></a>
            {% endif %}
            {% for i in estudiantes.paginator.page_range %}
            {% if estudiantes.number == i %}
            <a class="rounded-circle bg-Cprimary text-white d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="" disabled>{{ i }}</a>
            {% else %}
            <a class="rounded-circle border-0 text-black-50 d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="?{{request.GET.urlencode}}&page={{ i }}">{{ i }}</a>
            {% endif %}
            {% endfor %}
            {% if estudiantes.has_next%}
            <a class="border-0 text-Cprimary d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="?{{request.GET.urlencode}}&page={{ estudiantes.next_page_number }}"><i
                class="fa fa-step-forward"></i></a>
            {% endif %}
            {% if estudiantes.has_next %}
            <a class="border-0 text-Cprimary d-flex justify-content-center align-items-center px-2 mx-1 my-1 paginatorH"
              href="?{{request.GET.urlencode}}&page={{ estudiantes.paginator.num_pages }}"><i
                class="fa fa-fast-forward"></i></a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

admin/templates/profiles/readTipoDocumento.html
{% extends 'general/master.html' %}
{% block content %}
<div class="container">
    <div class="row mx-0 mt-4 mb-2">
        <div class="col-6 col-md-0 px-0">
            <h2><b> Tipos de Documentos </b></h2>
        </div>
    </div>
    <div class="row mx-0">
        <div class="col-12 p-0">
          <div class="table-responsive">
            <div class="table-wrapper">
              <div class="row mx-0">
                <table class="table table-hover">
                  <thead>
                    <tr class="bg-Cprimary text-justify text-light shadow">
                      <th class="align-middle text-center">ID</th>
                      <th class="align-middle text-center">Nombre</th>        
                    </tr>
                  </thead>
                  <tbody>
                    {% for tipoDocumento in tipoDocumentos %}
                    <tr class="table-light text-justify">
                        <td class="align-middle text-center">{{tipoDocumento.id}}</td>
                        <td class="align-middle text-center">{{tipoDocumento.nombre_documento}}</td>
                      </td>
                    </tr>                            
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
</div>
{% endblock %}